### ISSUE TITLE
Getting 'GET' request returning malformed JSON error.

### ISSUE THREAD

**Issue by faraco** [ironcamel/WebService-Client#13]
Hi, I am a user of WebService::Client 0.0501 and 0.0502, but after the latest update, I got malformed JSON error right away when using my module that is based on this distribution. I take a look at the version I upgraded, and it is 0.0600, and on the spot took a test on using the examples that requests JSON from MetaCPAN API -

lib/Test.pm
---
```perl
package Test;
use Moo;
with 'WebService::Client';

has '+base_url' => (
	default => 'https://fastapi.metacpan.org/v1'
);

sub get_json {
	my $self = shift;
	return $self->get("/distribution/_search");
}

1;

```

user_wc.pl
---
```perl
use Modern::Perl;
use Data::Dumper;
use lib 'lib';
use Test;

my $t = Test->new;

print Dumper $t->get_json;

```

returned error
---
```bash
$ perl user_wc.pl
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at /home/faraco/perl5/lib/perl5/WebService/Client.pm line 55.
```
I'm not sure if I did any mistake that causes this malformed error, but I'm pretty sure my untouched code run just fine with version 0.0501 and 0.0502. Maybe I missed a _required_ switch somewhere?

Thank you for taking time reviewing this issue.

Best regards,
faraco

**Comment by ironcamel** [comment]
Thanks for telling me about this. I fixed it in https://github.com/ironcamel/WebService-Client/commit/a86219e52830ddddad430beecca5dea4a8599d3e and pushed it to CPAN.

**Comment by faraco** [comment]
Thanks. It works now.
